name: Deploy to Elastic Beanstalk - Java Corretto Application

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  APPLICATION_NAME: corretto-app
  ENVIRONMENT_NAME: corretto-app-env

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up JDK Corretto
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package assembly:single

      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp target/sample-app-1.0-jar-with-dependencies.jar deploy/
          cp Procfile deploy/
          cp -r .ebextensions deploy/
          cd deploy
          zip -r ../app.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.APPLICATION_NAME }}
          environment-name: ${{ env.ENVIRONMENT_NAME }}
          version-label: corretto-${{ github.sha }}
          solution-stack-name: '64bit Amazon Linux 2023 v4.3.0 running Corretto 21'
          deployment-package-path: app.zip
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              }
            ]
